(() => {
  const sb = window.primeSupabase;
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const orgNames = {sahp:'SAHP',lspd:'LSPD',ng:'NG',li:'LI',ballas:'Ballas','marabunta-grande':'Marabunta Grande',vagos:'Vagos',families:'Families',bloods:'Bloods'};
  let currentRole='player';
  function message(text,error=false){const el=$('applicationMessage');if(el){el.textContent=text;el.style.color=error?'#ff6b7a':'';}}
  async function getUser(){if(!sb)throw new Error('Supabase is not configured.');const {data,error}=await sb.auth.getUser();if(error)throw error;return data?.user||null;}
  async function loadRole(id){const {data,error}=await sb.from('profiles').select('role').eq('id',id).maybeSingle();if(error)throw error;currentRole=data?.role||'player';const select=$('organization'),label=document.querySelector('label[for="organization"]');if(currentRole==='admin'){select?.removeAttribute('required');if(label)label.textContent='Organization (optional for admins)';if(select&&!document.getElementById('adminOrgHelp')){const h=document.createElement('small');h.id='adminOrgHelp';h.className='text-muted';h.textContent='Admin mode: leave this on “Select an organization” for an unassigned application.';select.insertAdjacentElement('afterend',h);}}}
  async function loadApplications(){const grid=$('applicationsGrid');if(!grid)return;if(!sb){grid.innerHTML='<div class="forum-empty">Supabase is not configured.</div>';return;}const {data,error}=await sb.from('org_leader_applications').select('id,organization_name,organization_slug,status,answers,created_at').order('created_at',{ascending:false});if(error){grid.innerHTML=`<div class="forum-empty">${esc(error.message)}</div>`;return;}grid.innerHTML=(data||[]).map(a=>{const answer=typeof a.answers==='object'?(a.answers.application||a.answers.summary||''):String(a.answers||'');const status=String(a.status||'pending').replace('_',' ').toUpperCase();return `<a class="app-card" href="application.html?id=${encodeURIComponent(a.id)}" aria-label="Open ${esc(a.organization_name||orgNames[a.organization_slug]||'Organization')} application"><span class="status">${esc(status)} · EN1</span><h3>${esc(a.organization_name||orgNames[a.organization_slug]||'Organization')}</h3><p>${esc(answer).slice(0,420)}${String(answer).length>420?'…':''}</p><small class="text-muted">Posted ${new Date(a.created_at).toLocaleDateString()} · Click to view application →</small></a>`;}).join('')||'<div class="forum-empty">No applications have been posted yet.</div>';}
  async function submitApplication(e){e.preventDefault();message('Submitting...');try{if(!sb)throw new Error('Supabase is not configured.');const user=await getUser();if(!user){location.href='login.html?redirect=applications.html';return;}await loadRole(user.id);const slug=($('organization')?.value||'').trim(),text=($('applicationAnswers')?.value||'').trim();if(!text){message('Complete your application before submitting.',true);return;}if(!slug&&currentRole!=='admin'){message('Please select an organization.',true);return;}const applicationSlug=slug||'unassigned',applicationName=slug?(orgNames[slug]||slug):'Unassigned';const button=$('applicationForm')?.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Submitting...';}const {error}=await sb.from('org_leader_applications').insert({applicant_id:user.id,organization_name:applicationName,organization_slug:applicationSlug,answers:{application:text}});if(button){button.disabled=false;button.textContent='Submit Application';}if(error)throw error;$('applicationAnswers').value='';if($('organization'))$('organization').value='';message('Application posted successfully.');await loadApplications();}catch(err){console.error('Prime Roleplay application submission error:',err);message(`Submission failed: ${err?.message||String(err)}`,true);const button=$('applicationForm')?.querySelector('button[type="submit"]');if(button){button.disabled=false;button.textContent='Submit Application';}}}
  async function init(){try{if(sb){const user=await getUser();if(user)await loadRole(user.id);}}catch(err){console.error(err);}$('applicationForm')?.addEventListener('submit',submitApplication);await loadApplications();}
  init();
})();
